# Generated by Django 2.0.13 on 2019-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trellouser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
