# Generated by Django 2.0.13 on 2019-10-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='boardList',
        ),
        migrations.RemoveField(
            model_name='boardlist',
            name='listCard',
        ),
        migrations.AddField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.Board'),
        ),
        migrations.AddField(
            model_name='listcard',
            name='board_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.BoardList'),
        ),
    ]
