# Generated by Django 2.0.13 on 2019-10-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_trellouser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
