# Generated by Django 2.0.13 on 2019-10-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_listcard_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
