# Generated by Django 2.0.13 on 2019-10-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0005_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('AL', 'Add List'), ('EL', 'Edit List'), ('AC', 'Add Card'), ('Edited Card', 'Edit Card'), ('ARCH', 'Archive Card')], max_length=1),
        ),
    ]
