# Generated by Django 2.0.13 on 2019-10-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0006_auto_20191011_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('AL', 'Add List'), ('EL', 'Edit List'), ('added card', 'Add Card'), ('edited card', 'Edit Card'), ('ARCH', 'Archive Card')], max_length=1),
        ),
    ]
