# Generated by Django 2.0.13 on 2019-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0007_auto_20191011_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('added list', 'Add List'), ('edited list', 'Edit List'), ('added card', 'Add Card'), ('edited card', 'Edit Card'), ('archived list', 'Archive Card')], max_length=1),
        ),
    ]
