# Generated by Django 2.0.13 on 2019-10-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0010_boardmembers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmembers',
            options={'permissions': (('can_add_card', 'Can add card'), ('can_edit_card', 'Can edit card'), ('can_add_list', 'Can add list'), ('can_edit_list', 'Can edit list'))},
        ),
    ]
