# Generated by Django 2.0.13 on 2019-10-14 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0013_auto_20191014_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembers',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
