# Generated by Django 2.0.13 on 2019-10-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0014_auto_20191014_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmembers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trellouser',
            options={'permissions': (('can_add_card', 'Can add card'), ('can_edit_card', 'Can edit card'))},
        ),
    ]
