# Generated by Django 2.0.13 on 2019-10-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0015_auto_20191014_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trellouser',
            options={'permissions': (('can_add_card', 'Can add card'), ('can_edits_card', 'Can edit card'))},
        ),
    ]
