# Generated by Django 2.0.13 on 2019-10-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0020_auto_20191014_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trellouser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='trellouser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='trellouser',
            name='user_permissions',
        ),
    ]
