# Generated by Django 2.0.13 on 2019-10-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0024_auto_20191014_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcard',
            options={'default_permissions': ('add',)},
        ),
    ]
