# Generated by Django 2.0.13 on 2019-10-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0027_auto_20191014_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcard',
            options={'permissions': (('can_add_card', 'Can add card'), ('can_edit_card', 'Can edit card'))},
        ),
    ]
