# Generated by Django 2.0.13 on 2019-10-14 12:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0028_auto_20191014_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.Board')),
            ],
        ),
        migrations.AlterModelOptions(
            name='boardmembers',
            options={},
        ),
    ]
