# Generated by Django 2.0.13 on 2019-10-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0029_auto_20191014_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardinvite',
            old_name='id',
            new_name='uuid',
        ),
    ]
