# Generated by Django 2.0.13 on 2019-10-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0030_auto_20191014_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcard',
            options={},
        ),
    ]
