# Generated by Django 2.0.13 on 2019-10-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0031_auto_20191014_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttatchments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello.ListCard')),
            ],
        ),
    ]
