# Generated by Django 2.0.13 on 2019-10-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0032_cardattatchments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.FileField(null=True, upload_to='files/')),
            ],
        ),
        migrations.AlterField(
            model_name='listcard',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cardchecklist',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello.ListCard'),
        ),
    ]
