# Generated by Django 2.0.13 on 2019-10-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0034_auto_20191017_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardchecklist',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
