# Generated by Django 2.0.13 on 2019-10-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0035_cardchecklist_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.Board'),
        ),
    ]
